# Generated by Django 6.1.1 on 2026-09-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_resume_company_remove_resume_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='target_position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
