# Generated by Django 6.1.1 on 2026-09-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_target_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='accomplishments',
            field=models.TextField(blank=True, help_text='Key achievements, skills learned, or notable accomplishments (comma-separated)', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=200),
        ),
    ]
